/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Database.DatabaseConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Phillip
 */
public class ItemForm extends javax.swing.JFrame {

    /**
     * Creates new form ItemForm
     */
    Connection con;
    DatabaseConnection DBCon;
    PreparedStatement pst;
    ResultSet rs;
    
    public ItemForm() {
        initComponents();
        DBCon = new DatabaseConnection();
        con = DBCon.getConnection();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_itemName = new javax.swing.JLabel();
        textfield_itemName = new javax.swing.JTextField();
        label_price = new javax.swing.JLabel();
        textfield_price = new javax.swing.JTextField();
        label_quantity = new javax.swing.JLabel();
        textfield_quantity = new javax.swing.JTextField();
        button_itemAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_item = new javax.swing.JTable();
        button_itemSave = new javax.swing.JButton();

        setLocation(new java.awt.Point(250, 250));

        label_itemName.setText("Item name: ");

        label_price.setText("Price: ");

        label_quantity.setText("Quantity: ");

        button_itemAdd.setText("Add");
        button_itemAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_itemAddActionPerformed(evt);
            }
        });

        table_item.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Price", "Quantity", "Total Amount"
            }
        ));
        jScrollPane1.setViewportView(table_item);
        if (table_item.getColumnModel().getColumnCount() > 0) {
            table_item.getColumnModel().getColumn(0).setResizable(false);
            table_item.getColumnModel().getColumn(1).setResizable(false);
            table_item.getColumnModel().getColumn(2).setResizable(false);
        }

        button_itemSave.setText("Save");
        button_itemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_itemSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_quantity)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(button_itemAdd)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(label_itemName)
                                        .addComponent(label_price))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textfield_itemName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(textfield_quantity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                            .addComponent(textfield_price, javax.swing.GroupLayout.Alignment.LEADING))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(button_itemSave)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_itemName)
                            .addComponent(textfield_itemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_price)
                            .addComponent(textfield_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_quantity)
                            .addComponent(textfield_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_itemAdd))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(button_itemSave)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_itemAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_itemAddActionPerformed
        // TODO add your handling code here:
        String itemName = textfield_itemName.getText();
        double price =  Double.parseDouble(textfield_price.getText());
        double quantity = Double.parseDouble(textfield_quantity.getText());
        
        Object[] row = new Object[4];
        DefaultTableModel model = (DefaultTableModel)table_item.getModel();
        
        row[0] = itemName;
        row[1] = price;
        row[2] = quantity;
        row[3] = price * quantity;
        
        model.addRow(row);
        
        textfield_itemName.setText("");
        textfield_price.setText("");
        textfield_quantity.setText("");
    }//GEN-LAST:event_button_itemAddActionPerformed

    private void button_itemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_itemSaveActionPerformed
        // TODO add your handling code here:
        
         try {
            int rows = table_item.getRowCount();
            System.out.println(rows);
            
            for (int row=0;row<rows;row++) {
                String itemName = (String) table_item.getValueAt(row, 0);
                double price= (double)table_item.getValueAt(row, 1);
                double quantity = (double) table_item.getValueAt(row, 2);
                double amount = (double) table_item.getValueAt(row, 3);
                
                String query = "Insert into inventory (name, price, quantity, amount) values ('" + itemName + "', '" + price + "', '" + quantity + "', '" + amount + "')";
                
                pst = con.prepareStatement(query);
                pst.execute();
            }
            JOptionPane.showMessageDialog(null, "Sucessfully saved");
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_button_itemSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_itemAdd;
    private javax.swing.JButton button_itemSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_itemName;
    private javax.swing.JLabel label_price;
    private javax.swing.JLabel label_quantity;
    private javax.swing.JTable table_item;
    private javax.swing.JTextField textfield_itemName;
    private javax.swing.JTextField textfield_price;
    private javax.swing.JTextField textfield_quantity;
    // End of variables declaration//GEN-END:variables
}
